name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:     # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pac-Man Contribution Graph
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          # GitHub username
          github_user_name: ${{ github.repository_owner }}
          # path of the generated svg
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
          # dark mode Pac-Man theme
